spring:
  application:
    name: ticket-api
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
eureka:
  instance:
    hostname: localhost
  client:
    registerWtihEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka