spring:
  application:
    name: zuul_gateway
server:
  port: 8000
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
zuul:
  host:
    connect-timeout-millis: 10000000
    socket-timeout-millis: 10000000
  ignoredServices: '*'
  routes:
    users-api:
      path: /users-api/**
      serviceId: users-api
      stripPrefix: false
    ticket-api:
      path: /incident-api/**
      serviceId: ticket-api
      stripPrefix: false
